export const skills={
    Languages:[
        {
            name:"Javascript",
            years:3.5,
            proficieny:3
        },
        {
            name:"HTML",
            years:4,
            proficieny:3
        },
        {
            name:"CSS",
            years:4,
            proficieny:3
        },
        {
            name:"Java",
            years:1.5,
            proficieny:2
        },
        {
            name:"Python",
            years:1.5,
            proficieny:1
        },
        {
            name:"PostgreSQL",
            years:1.5,
            proficieny:2
        },
    ],
    Frameworks:[
        {
            name:"React",
            years:2,
            proficieny:3
        },
        {
            name:"GraphQL",
            years:1.5,
            proficieny:2
        },
        {
            name:"Spring",
            years:1.5,
            proficieny:1
        },
        {
            name:"MS SharePoint",
            years:2,
            proficieny:2
        },
    ],
    ["Libraries, Runtimes, Software"]:[
        {
            name:"AWS",
            years:1.5,
            proficieny:2
        },
        {
            name:"Git",
            years:3.5,
            proficieny:3
        },
        {
            name:"Github",
            years:3.5,
            proficieny:3
        },
        {
            name:"Elasticsearch",
            years:1.5,
            proficieny:1
        },
        {
            name:"jenkins",
            years:1.5,
            proficieny:1
        },
        {
            name:"npm",
            years:2,
            proficieny:3
        },
        {
            name:"node.js",
            years:2,
            proficieny:2
        },
        {
            name:"express",
            years:2,
            proficieny:2
        },
        {
            name:"Jira",
            years:1.5,
            proficieny:2
        },
        {
            name:"mui",
            years:1.5,
            proficieny:3
        },
        {
            name:"bootstrap",
            years:3.5,
            proficieny:3
        },
        {
            name:"jQuery",
            years:3,
            proficieny:3
        },
        
    ]
}

export const proficiencyKey =
[
    "novice",
    "beginner",
    "intermediate",
    "advanced",
    "master",
]